# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(null=True)),
                ('timeslot', models.CharField(choices=[('09:00', '09:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('15:00', '15:00')], default='09:00', max_length=25)),
                ('style', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hairappointment',
            unique_together=set([('date', 'timeslot')]),
        ),
    ]
