# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20170818_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairappointment',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.Availability'),
        ),
    ]
