# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairappointment',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Services'),
        ),
    ]
