# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20170820_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='styles',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
